# Generated by Django 6.0.3 on 2026-03-21 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sprites', models.ImageField(upload_to='sprites/')),
                ('type1', models.CharField(max_length=10)),
                ('type2', models.CharField(blank=True, max_length=10, null=True)),
                ('hp', models.IntegerField()),
                ('attack', models.IntegerField()),
                ('defense', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('abilites', models.TextField()),
            ],
        ),
    ]
