# Generated by Django 6.0.3 on 2026-03-21 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pokedex', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='sprite_img',
            field=models.ImageField(blank=True, null=True, upload_to='sprites/'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='sprites',
            field=models.TextField(),
        ),
    ]
