# Generated by Django 6.0.3 on 2026-03-21 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_pokedex', '0002_pokemon_sprite_img_alter_pokemon_sprites'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='abilites',
            new_name='abilities',
        ),
    ]
