# Generated by Django 6.0.3 on 2026-03-21 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pokedex', '0003_rename_abilites_pokemon_abilities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type1',
            field=models.CharField(max_length=11),
        ),
    ]
