# Generated by Django 6.0.3 on 2026-03-21 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pokedex', '0004_alter_pokemon_type1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='sprites',
            field=models.TextField(blank=True, null=True),
        ),
    ]
