# Generated by Django 6.0.3 on 2026-03-23 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pokedex', '0007_delete_usuarios_pokemon_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='id_pokeapi',
            field=models.TextField(blank=True, null=True),
        ),
    ]
